services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    env_file:
      - ./.env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

  app:
    build: .
    depends_on:
      - db
      - minio
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      - S3_ENDPOINT=http://minio:9000
    ports:
      - "8080:8080"
