name: CI • Build & Integration (PR)

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BIN_NAME: mealmind

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Build (release)
        run: cargo build --release --workspace --all-features --locked

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-linux-amd64-${{ github.sha }}
          path: target/release/${{ env.BIN_NAME }}
          if-no-files-found: error
          retention-days: 14

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_release
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: mealmind_test
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U test -d mealmind_test"
          --health-interval 5s --health-timeout 5s --health-retries 20
      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: test
          MINIO_ROOT_PASSWORD: testtest123
        ports: ['9000:9000','9001:9001']
        options: >-
          --health-cmd "curl -sf http://localhost:9000/minio/health/ready || exit 1"
          --health-interval 5s --health-timeout 5s --health-retries 20
        command: server /data --console-address ":9001"

    steps:
      - uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: mealmind-linux-amd64-${{ github.sha }}
          path: ./bin

      - name: Make binary executable
        run: chmod +x ./bin/mealmind

      - name: Run integration suite (blackbox)
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/mealmind_test
          MINIO_ENDPOINT: http://localhost:9000
          MINIO_KEY: test
          MINIO_SECRET: testtest123
        run: |
          ./bin/mealmind --config ci-config.toml &
          sleep 5
          curl -f http://localhost:8080/health
