name: CI • Rust Build, Test & Audit (no tags)

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BIN_NAME: mealmind

jobs:
  build_test_audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy,rustfmt

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: mealmind-linux-release
          cache-on-failure: true
          save-if: "always()"

      - name: Lint (fmt + clippy)
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features --workspace --release -- -D warnings

      - name: Test (release)
        run: cargo test --release --all-features --workspace --locked --quiet

      - name: Security audit (cargo-audit)
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
