name: CI • Rust Build & Test (no tags)

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BIN_NAME: mealmind

jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy,rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features --workspace --release -- -D warnings

      - name: Test (release)
        run: cargo test --release --all-features --workspace --locked --quiet